# Generated by Django 4.1.7 on 2023-05-09 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='company_email',
            field=models.EmailField(blank=True, max_length=50, null=True, verbose_name='company email address'),
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='company_name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
